### ISSUE TITLE
Exporting Spring Boot project to a single executable file

### ISSUE THREAD

**Issue by saurabhagrawal0412** [airavata-courses/nikchett#1]
Hi,
You wouldn't want your reviewers to watch the [Youtube playlist]( https://www.youtube.com/watch?v=msXL2oDexqw&list=PLqq-6Pq4lTTbx8p2oCgcAQGQyqN8XeA1x) to understand how to deploy the application.
I suggest that you export the whole Spring Boot app to a single jar file.

Thanks

**Comment by saurabhagrawal0412** [comment]
As discussed I saw the videos and executed the application, and it worked.
![nickreview](https://user-images.githubusercontent.com/19391379/29951477-e968cda0-8e90-11e7-8e9c-5964919353d3.jpg)

But, do update the README and try to make one executable jar.

**Comment by nikchett** [comment]
Thanks a lot Saurabh ! I appreciate your efforts .   I will try to create an executable jar and will update the Readme to make the installation easy

**Comment by saurabhagrawal0412** [comment]
@nikchett ,
Please close the issue if you are done with this.

Thanks
