### ISSUE TITLE
Assignment 2 Comments

### ISSUE THREAD

**Issue by tilaks26** [airavata-courses/nikchett#7]
- I have been looking into the master branch to grade Assignment 2, please let me know if there is another branch I should be looking into.
- Where have you defined rabbithost to which you are connecting from the microservices and API gateway?
- Can you please share your Jenkins credentials so that I can look into your build?

**Comment by nikchett** [comment]
Hi Sneha,
The following are the different branches for the assignment 2 projects.
*/ui 
*/microservice
*/microservice1
*/gateway

The rabbit host is running on the vm instances on a docker container. 

The credentials are username : nikchett and pwd : user123. I have added the credentials in the submission comments.

Please let me know if u need more information.

**Comment by tilaks26** [comment]
Thank you. This is sufficient.
